/*
 * expIntDecls.h --
 *
 *	Declarations of functions in the platform independent public
 *	Expect API.
 *
 * See the file "license.terms" for information on usage and redistribution
 * of this file, and for a DISCLAIMER OF ALL WARRANTIES.
 *
 * RCS: $Id: itclDecls.h,v 1.3 2001/09/16 15:02:41 davygrvy Exp $
 */

#ifndef _EXPINTDECLS_H__
#define _EXPINTDECLS_H__

/*
 * WARNING: This file is automatically generated by the tools/genStubs.tcl
 * script.  Any modifications to the function declarations below should be made
 * in the itcl/generic/tcl.decls script.
 */

/* !BEGIN!: Do not edit below this line. */
/* !END!: Do not edit above this line. */

#endif /* _EXPINTDECLS_H__ */
